on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      working_directory:
        required: true
        type: string
    secrets:
      GOOGLE_CREDENTIALS:
        required: true
      GOOGLE_PROJECT:
        required: true

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'install tf'
      uses: hashicorp/setup-terraform@v2

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.3.0
      with:
        terragrunt_version: latest

    - name: Interact with Terragrunt
      run: terragrunt --version

    - name: 'install python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 'install poetry'
      run: |
        pip install -U pip
        pip install poetry
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: 'tg init'
      run: terragrunt init
      working-directory: ${{ inputs.working_directory }}
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: 'tg validate'
      run: terragrunt validate
      working-directory: ${{ inputs.working_directory }}
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: 'tg plan'
      run: terragrunt plan -var="project=$GOOGLE_PROJECT"
      working-directory: ${{ inputs.working_directory }}
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}

    - name: 'tg apply'
      run: |
        terragrunt apply --auto-approve -var="project=$GOOGLE_PROJECT"
      working-directory: ${{ inputs.working_directory }}
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}