name: 'terraform ci'

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'install tf'
      uses: hashicorp/setup-terraform@v1

    - name: 'tf init'
      run: terraform init
      working-directory: terraform
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: 'tf plan'
      run: terraform plan -var="billing_alert_email=$BILLING_ALERT_EMAIL" -var="project=$GOOGLE_PROJECT"
      working-directory: terraform
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        BILLING_ALERT_EMAIL: ${{ secrets.BILLING_ALERT_EMAIL }}
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}

    - name: 'tf apply'
      run: |
        echo "$BILLING_ALERT_EMAIL $GOOGLE_PROJECT"
        terraform apply --auto-approve -var="billing_alert_email=$BILLING_ALERT_EMAIL" -var="project=$GOOGLE_PROJECT"
      working-directory: terraform
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        BILLING_ALERT_EMAIL: ${{ secrets.BILLING_ALERT_EMAIL }}
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}

  e2e:
    name: e2e
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
      working-directory: cloud_functions

    - name: Test with pytest
      run: pytest e2e/
      working-directory: cloud_functions