name: 'terraform ci'

on:
  push:
    branches:
      - master
    paths-ignore:
      - .devcontainer/**
      - weather-station-gcp/**
      - .gitignore
      - viz/**

concurrency: 'workflow'

jobs:
  terraform-init:
    name: 'Bootstrap infra'
    uses: nagyben/wemos-bmp280/.github/workflows/deploy.yaml@master
    with:
      environment: init
      working_directory: infra/init
    secrets:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}

  receiver-unit-test:
    name: 'Receiver unit test'
    runs-on: ubuntu-latest
    needs: [terraform-init]

    services:
      firestore:
        image: mtlynch/firestore-emulator
        ports:
          - 8080:8080

      gcs:
        image: europe-west2-docker.pkg.dev/nagyben/nagyben-cr/fake-gcs
        ports:
          - 8090:8090

        # see https://cloud.google.com/artifact-registry/docs/docker/authentication#json-key
        credentials:
          username: _json_key_base64
          password: ${{ secrets.DOCKER_REGISTRY_KEY_BASE64 }}

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'install python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 'install test dependencies'
      run: |
        pip install -U pip
        pip install poetry
        poetry lock
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false
      working-directory: cloud_functions/receiver

    - name: 'code quality'
      run: |
        set -euo pipefail
        black --check .
        isort --check .
        mypy --strict .
      working-directory: cloud_functions/receiver

    - name: 'pytest'
      run: |
        python -m pytest tests/ -vs
      working-directory: cloud_functions/receiver
      env:
        FIRESTORE_EMULATOR_HOST: localhost:8080
        FIRESTORE_PROJECT_ID: dummy-firestore-id
        PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python

  viz-unit-test:
    name: 'Viz unit test'
    runs-on: ubuntu-latest
    needs: [terraform-init]

    services:
      firestore:
        image: mtlynch/firestore-emulator
        ports:
          - 8080:8080

      gcs:
        image: europe-west2-docker.pkg.dev/nagyben/nagyben-cr/fake-gcs
        ports:
          - 8090:8090

        # see https://cloud.google.com/artifact-registry/docs/docker/authentication#json-key
        credentials:
          username: _json_key_base64
          password: ${{ secrets.DOCKER_REGISTRY_KEY_BASE64 }}

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'install python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 'install test dependencies'
      run: |
        pip install -U pip
        pip install poetry
        poetry lock
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false
      working-directory: cloud_functions/viz

    - name: 'code quality'
      run: |
        set -euo pipefail
        black --check .
        isort --check .
        mypy --strict .
      working-directory: cloud_functions/viz

    - name: 'pytest'
      run: |
        python -m pytest tests/ -vs
      working-directory: cloud_functions/viz
      env:
        FIRESTORE_EMULATOR_HOST: localhost:8080
        FIRESTORE_PROJECT_ID: dummy-firestore-id
        STORAGE_EMULATOR_HOST: http://localhost:8090

    - name: 'install playwright'
      run: |
        playwright install
      working-directory: cloud_functions/viz

    - name: 'UI tests'
      run: |
        python -m pytest ui_tests/
      working-directory: cloud_functions/viz

    - name: Dump docker logs on failure
      if: failure()
      uses: jwalton/gh-docker-logs@v1

  terraform-deploy-test:
    name: 'Deploy test infra'
    uses: nagyben/wemos-bmp280/.github/workflows/deploy.yaml@master
    needs: [receiver-unit-test, viz-unit-test]
    with:
      environment: test
      working_directory: infra/app-test
    secrets:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}

  e2e:
    name: e2e
    runs-on: ubuntu-latest
    needs: terraform-deploy-test

    steps:
    - uses: actions/checkout@v3

    - name: 'install tf'
      uses: hashicorp/setup-terraform@v2
      with:
        # https://stackoverflow.com/questions/71462777/parse-error-when-trying-to-parse-terraform-output-in-github-actions-workflow-wit
        terraform_wrapper: false

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.3.0
      with:
        terragrunt_version: latest

    - name: 'tf init'
      run: terragrunt init
      working-directory: infra/app-test
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: 'tf output'
      run: terragrunt output -json > /tmp/tfoutput.json
      working-directory: infra/app-test
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: 'install python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 'install test dependencies'
      run: |
        set -euo pipefail
        pip install -U pip
        pip install poetry
        poetry lock
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false
      working-directory: cloud_functions/e2e

    - run: echo $GOOGLE_CREDENTIALS > /tmp/creds.json
      name: write creds to file
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Test with pytest
      run: |
        set -euo pipefail
        export RECEIVER_URL=$(jq -r .receiver_url.value /tmp/tfoutput.json)
        export TOPIC_NAME=$(jq -r .topic_name.value /tmp/tfoutput.json)
        export URL=$(jq -r ".viz_url.value" /tmp/tfoutput.json)
        export STATIC_SITE_BUCKET=$(jq -r ".static_site_bucket_name.value" /tmp/tfoutput.json)
        python -m pytest .
      working-directory: cloud_functions/e2e
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/creds.json

  terraform-deploy-prod:
    name: 'Deploy prod infra'
    uses: nagyben/wemos-bmp280/.github/workflows/deploy.yaml@master
    needs: [e2e]
    with:
      environment: prod
      working_directory: infra/app-prod
    secrets:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
