name: 'terraform ci'

on:
  push:
    branches:
      - master

concurrency: 'workflow'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'install tf'
      uses: hashicorp/setup-terraform@v1

    - name: 'export requirements'
      run: |
        pip install -U pip
        pip install poetry
        poetry lock
        poetry export --without-hashes > requirements.txt
      env:
        POETRY_VIRTUALENVS_CREATE: false
      working-directory: cloud_functions

    - name: 'tf init'
      run: terraform init
      working-directory: terraform
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: 'tf plan'
      run: terraform plan -var="billing_alert_email=$BILLING_ALERT_EMAIL" -var="project=$GOOGLE_PROJECT"
      working-directory: terraform
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        BILLING_ALERT_EMAIL: ${{ secrets.BILLING_ALERT_EMAIL }}
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}

    - name: 'tf apply'
      run: |
        echo "$BILLING_ALERT_EMAIL $GOOGLE_PROJECT"
        terraform apply --auto-approve -var="billing_alert_email=$BILLING_ALERT_EMAIL" -var="project=$GOOGLE_PROJECT"
      working-directory: terraform
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        BILLING_ALERT_EMAIL: ${{ secrets.BILLING_ALERT_EMAIL }}
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}

  e2e:
    name: e2e
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - uses: actions/checkout@v2

    - name: 'install tf'
      uses: hashicorp/setup-terraform@v1

    - name: 'tf init'
      run: terraform init
      working-directory: terraform
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: 'tf output'
      run: terraform-bin output -json > tfoutput.json
      working-directory: terraform
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pytest dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
      working-directory: cloud_functions

    - run: echo $GOOGLE_CREDENTIALS > /tmp/creds.json
      name: write creds to file
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Test with pytest
      run: |
        cat ../terraform/tfoutput.json
        export RECEIVER_URL=$(jq -r ".receiver_url.value" ../terraform/tfoutput.json)
        pytest e2e/
      working-directory: cloud_functions
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/creds.json